dataset: ogbnarxiv
data:
  graph_dataset:
    ogbnarxiv: /Users/macsaumya/Documents/BTP/Model and Data/edgehetero-nodeproppred/data/ogbnarxiv_heterodata_v2.pt
node_embs: preloaded_in_graph
edge_type_selection:
  ogbnarxiv:
  - references
  - author
  - venue
  - fos
optimizer:
  lr: 0.001
  weight_decay: 0
model:
  name: SAGE
  hidden_channels: 128
  num_layers: 2
  dropout: 0.5
early_stop_threshold: 15
epochs: 200
runs: 1
